---
AWSTemplateFormatVersion: 2010-09-09
Description: Provisions HIPAA Ready Environment in AWS (qs-1qtukbnsl)
Metadata:
  LintSpellExclude:
    - CloudWatch
    - CloudTrail
  Identifier:
    Value: main
  Input:
    Description: Input of all required parameters in nested stacks
  Output:
    Description: N/A
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: AWS config configuration
      Parameters:
      - AWSConfigARN
    - Label:
        default: AWS logging configuration
      Parameters:
      - SNSAlarmEmail
      - LifecycleExpirationDays
      - LifecycleTransitionStandardIADays
      - LifecycleTransitionGlacierDays
      - CloudTrailLogRetentionDays
    - Label:
        default: Development VPC configuration
      Parameters:
      - DevVPCCIDRBlock
      - DevVPCSubnet1
      - DevVPCSubnet2
      - DevVPCFlowLogLogGroup
      - DevVPCFlowLogLogGroupRetention
    - Label:
        default: Production VPC configuration
      Parameters:
      - ProdVPCCIDRBlock
      - ProdVPCSubnet1
      - ProdVPCSubnet2
      - ProdVPCFlowLogLogGroup
      - ProdVPCFlowLogLogGroupRetention
    - Label:
        default: Management VPC configuration
      Parameters:
      - MgmtVPCCIDRBlock
      - MgmtVPCPublicSubnet1
      - MgmtVPCPublicSubnet2
      - MgmtVPCPrivateSubnet1
      - MgmtVPCPrivateSubnet2
      - MgmtVPCFlowLogLogGroup
      - MgmtVPCFlowLogLogGroupRetention
    - Label:
        default: AWS quick start configuration
      Parameters:
      - QSS3BucketName
      - QSS3BucketRegion
      - QSS3KeyPrefix
    ParameterLabels:
      AWSConfigARN:
        default: AWS config service linked role ARN
      SNSAlarmEmail:
        default: CloudWatch alarm notification email address
      LifecycleExpirationDays:
        default: S3 lifecycle expiration days
      LifecycleTransitionStandardIADays:
        default: S3 lifecycle transition to standard-IA days
      LifecycleTransitionGlacierDays:
        default: S3 lifecycle transition to glacier days
      CloudTrailLogRetentionDays:
        default: CloudTrail retention days
      DevVPCCIDRBlock:
        default: Development VPC CIDR block
      DevVPCSubnet1:
        default: Development Subnet 1 CIDR block
      DevVPCSubnet2:
        default: Development Subnet 2 CIDR block
      DevVPCFlowLogLogGroup:
        default: Development VPC log group
      DevVPCFlowLogLogGroupRetention:
        default: Development VPC log group retention days
      ProdVPCCIDRBlock:
        default: Production VPC CIDR block
      ProdVPCSubnet1:
        default: Production Subnet 1 CIDR block
      ProdVPCSubnet2:
        default: Production Subnet 2 CIDR block
      ProdVPCFlowLogLogGroup:
        default: Production VPC log group
      ProdVPCFlowLogLogGroupRetention:
        default: Production VPC log group retention days
      MgmtVPCCIDRBlock:
        default: Management VPC CIDR block
      MgmtVPCPublicSubnet1:
        default: Management public Subnet 1 CIDR block
      MgmtVPCPublicSubnet2:
        default: Management public Subnet 2 CIDR block
      MgmtVPCPrivateSubnet1:
        default: Management private Subnet 1 CIDR block
      MgmtVPCPrivateSubnet2:
        default: Management private Subnet 2 CIDR block
      MgmtVPCFlowLogLogGroup:
        default: Management VPC log group
      MgmtVPCFlowLogLogGroupRetention:
        default: Management VPC log group retention days
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
Parameters:
  AWSConfigARN:
    Type: String
    Default: ''
    Description: AWS config service linked role ARN.
  LifecycleExpirationDays:
    Type: Number
    Default: 2555
    Description: Lifecycle expiration days.
  LifecycleTransitionStandardIADays:
    Type: Number
    Default: 90
    Description: Lifecycle transition standard-IA days.
  LifecycleTransitionGlacierDays:
    Type: Number
    Default: 180
    Description: Lifecycle transition glacier days.
  SNSAlarmEmail:
    Type: String
    Default: ''
    Description: SNS security alarm email.
  CloudTrailLogRetentionDays:
    Type: Number
    Default: 90
    Description: CloudTrail log group retention days.
  DevVPCCIDRBlock:
    Type: String
    Default: 172.18.0.0/16
    Description: Development VPC CIDR block.
  DevVPCSubnet1:
    Type: String
    Default: 172.18.11.0/24
    Description: Development VPC Subnet 1.
  DevVPCSubnet2:
    Type: String
    Default: 172.18.12.0/24
    Description: Development VPC Subnet 2.
  DevVPCFlowLogLogGroup:
    Type: String
    Default: dev-flow-logs-group
    Description: Development VPC flow logs log group.
  DevVPCFlowLogLogGroupRetention:
    Type: Number
    Default: 90
    Description: Development VPC flow logs log group retention days.
  ProdVPCCIDRBlock:
    Type: String
    Default: 172.17.0.0/16
    Description: Production VPC CIDR block.
  ProdVPCSubnet1:
    Type: String
    Default: 172.17.11.0/24
    Description: Production VPC Subnet 1.
  ProdVPCSubnet2:
    Type: String
    Default: 172.17.12.0/24
    Description: Production VPC Subnet 2.
  ProdVPCFlowLogLogGroup:
    Type: String
    Default: prod-flow-logs-group
    Description: Production VPC flow logs log group.
  ProdVPCFlowLogLogGroupRetention:
    Type: Number
    Default: 90
    Description: Production VPC flow logs log group retention days.
  MgmtVPCCIDRBlock:
    Type: String
    Default: 172.16.0.0/16
    Description: Management VPC CIDR block.
  MgmtVPCPublicSubnet1:
    Type: String
    Default: 172.16.1.0/24
    Description: Management VPC public subnet 1.
  MgmtVPCPublicSubnet2:
    Type: String
    Default: 172.16.2.0/24
    Description: Management VPC public subnet 2.
  MgmtVPCPrivateSubnet1:
    Type: String
    Default: 172.16.11.0/24
    Description: Management VPC private subnet 1.
  MgmtVPCPrivateSubnet2:
    Type: String
    Default: 172.16.12.0/24
    Description: Management VPC private subnet 2.
  MgmtVPCFlowLogLogGroup:
    Type: String
    Default: mgmt-flow-logs-group
    Description: Management VPC flow logs log group.
  MgmtVPCFlowLogLogGroupRetention:
    Type: Number
    Default: 90
    Description: Management VPC flow logs log group retention days.
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-.]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, periods (.), and hyphens (-). It cannot start or
      end with a hyphen (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  QSS3BucketRegion:
    Default: us-east-1
    Description: The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: quickstart-compliance-hipaa/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
Resources:
  ConfigStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 
        !Sub 
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/config-stack.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
            QSS3KeyPrefix: !Ref QSS3KeyPrefix
      TimeoutInMinutes: 20
      Parameters:
        AWSConfigARN: !Ref AWSConfigARN
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
  LogStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 
        !Sub 
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/log-stack.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
            QSS3KeyPrefix: !Ref QSS3KeyPrefix
      TimeoutInMinutes: 20
      Parameters:
        SNSAlarmEmail: !Ref SNSAlarmEmail
        LifecycleExpirationDays: !Ref LifecycleExpirationDays
        LifecycleTransitionStandardIADays: !Ref LifecycleTransitionStandardIADays
        LifecycleTransitionGlacierDays: !Ref LifecycleTransitionGlacierDays
        CloudTrailLogRetentionDays: !Ref CloudTrailLogRetentionDays
  DevStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 
        !Sub 
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/dev-stack.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
            QSS3KeyPrefix: !Ref QSS3KeyPrefix
      TimeoutInMinutes: 20
      Parameters:
        DevVPCCIDRBlock: !Ref DevVPCCIDRBlock
        DevVPCSubnet1: !Ref DevVPCSubnet1
        DevVPCSubnet2: !Ref DevVPCSubnet2
        DevVPCFlowLogLogGroup: !Ref DevVPCFlowLogLogGroup
        DevVPCFlowLogLogGroupRetention: !Ref DevVPCFlowLogLogGroupRetention
  ProdStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 
        !Sub 
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/prod-stack.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
            QSS3KeyPrefix: !Ref QSS3KeyPrefix
      TimeoutInMinutes: 20
      Parameters:
        ProdVPCCIDRBlock: !Ref ProdVPCCIDRBlock
        ProdVPCSubnet1: !Ref ProdVPCSubnet1
        ProdVPCSubnet2: !Ref ProdVPCSubnet2
        ProdVPCFlowLogLogGroup: !Ref ProdVPCFlowLogLogGroup
        ProdVPCFlowLogLogGroupRetention: !Ref ProdVPCFlowLogLogGroupRetention
  MgmtStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 
        !Sub 
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/mgmt-stack.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
            QSS3KeyPrefix: !Ref QSS3KeyPrefix
      TimeoutInMinutes: 20
      Parameters:
        MgmtVPCCIDRBlock: !Ref MgmtVPCCIDRBlock
        MgmtVPCPublicSubnet1: !Ref MgmtVPCPublicSubnet1
        MgmtVPCPublicSubnet2: !Ref MgmtVPCPublicSubnet2
        MgmtVPCPrivateSubnet1: !Ref MgmtVPCPrivateSubnet1
        MgmtVPCPrivateSubnet2: !Ref MgmtVPCPrivateSubnet2
        MgmtVPCFlowLogLogGroup: !Ref MgmtVPCFlowLogLogGroup
        MgmtVPCFlowLogLogGroupRetention: !Ref MgmtVPCFlowLogLogGroupRetention
  TgwStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 
        !Sub 
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/tgw-stack.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
            QSS3KeyPrefix: !Ref QSS3KeyPrefix
      TimeoutInMinutes: 20
      Parameters:
        DevVPCCIDRBlock: !Ref DevVPCCIDRBlock
        ProdVPCCIDRBlock: !Ref ProdVPCCIDRBlock
        DevelopmentVPC:
          Fn::GetAtt: 
          - DevStack
          - Outputs.DevelopmentVPC
        DevelopmentVPCSubnet1:
          Fn::GetAtt: 
          - DevStack
          - Outputs.DevelopmentVPCSubnet1
        DevelopmentVPCSubnet2:
          Fn::GetAtt: 
          - DevStack
          - Outputs.DevelopmentVPCSubnet2
        DevelopmentPrivateRouteTable1:
          Fn::GetAtt: 
          - DevStack
          - Outputs.DevelopmentPrivateRouteTable1
        ProductionVPC:
          Fn::GetAtt: 
          - ProdStack
          - Outputs.ProductionVPC
        ProductionCoreSubnet1:
          Fn::GetAtt: 
          - ProdStack
          - Outputs.ProductionCoreSubnet1
        ProductionCoreSubnet2:
          Fn::GetAtt: 
          - ProdStack
          - Outputs.ProductionCoreSubnet2
        ProductionPrivateRouteTable1:
          Fn::GetAtt: 
          - ProdStack
          - Outputs.ProductionPrivateRouteTable1
        ManagementVPC:
          Fn::GetAtt: 
          - MgmtStack
          - Outputs.ManagementVPC
        ManagementCoreSubnet1:
          Fn::GetAtt: 
          - MgmtStack
          - Outputs.ManagementCoreSubnet1
        ManagementCoreSubnet2:
          Fn::GetAtt: 
          - MgmtStack
          - Outputs.ManagementCoreSubnet2
        ManagementPrivateRouteTable1:
          Fn::GetAtt: 
          - MgmtStack
          - Outputs.ManagementPrivateRouteTable1
        ManagementPrivateRouteTable2:
          Fn::GetAtt: 
          - MgmtStack
          - Outputs.ManagementPrivateRouteTable2
        ManagementPublicRouteTable1:
          Fn::GetAtt: 
          - MgmtStack
          - Outputs.ManagementPublicRouteTable1
        ManagementPublicRouteTable2:
          Fn::GetAtt: 
          - MgmtStack
          - Outputs.ManagementPublicRouteTable2
Outputs:
  TemplateType:
    Value: HIPAA Compliance
  TemplateVersion:
    Value: 1.0
  Help:
    Description: For assistance or questions regarding this quickstart please email compliance-accelerator@amazon.com
    Value: ''
...